-- Enable Row Level Security (RLS) is enabled by default on new tables in Supabase, but we explicity enable it.

-- 1. PROFILES TABLE (Single record for main user info)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null,
  role text,
  address text,
  phone text,
  email text,
  nationality text,
  summary text,
  social_linkedin text,
  social_github text,
  social_portfolio text,
  resume_url text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. EXPERIENCE TABLE
create table if not exists experience (
  id bigint generated by default as identity primary key,
  company text not null,
  position text not null,
  location text,
  description text,
  duration text,
  start_date date, -- Optional: for sorting if needed later
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table experience enable row level security;

create policy "Experience viewable by everyone." on experience for select using ( true );
create policy "Experience insertable by authenticated." on experience for insert with check ( auth.role() = 'authenticated' );
create policy "Experience updatable by authenticated." on experience for update using ( auth.role() = 'authenticated' );
create policy "Experience deletable by authenticated." on experience for delete using ( auth.role() = 'authenticated' );

-- 3. PROJECTS TABLE
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  tech text[], -- Array of strings
  github_url text,
  live_url text,
  featured boolean default false,
  year text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;

create policy "Projects viewable by everyone." on projects for select using ( true );
create policy "Projects insertable by authenticated." on projects for insert with check ( auth.role() = 'authenticated' );
create policy "Projects updatable by authenticated." on projects for update using ( auth.role() = 'authenticated' );
create policy "Projects deletable by authenticated." on projects for delete using ( auth.role() = 'authenticated' );

-- 4. EDUCATION TABLE
create table if not exists education (
  id bigint generated by default as identity primary key,
  degree text not null,
  university text not null,
  period text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table education enable row level security;

create policy "Education viewable by everyone." on education for select using ( true );
create policy "Education insertable by authenticated." on education for insert with check ( auth.role() = 'authenticated' );
create policy "Education updatable by authenticated." on education for update using ( auth.role() = 'authenticated' );
create policy "Education deletable by authenticated." on education for delete using ( auth.role() = 'authenticated' );

-- 5. SKILLS TABLE
create table if not exists skills (
  id bigint generated by default as identity primary key,
  category text not null, -- e.g. "Languages", "Frameworks"
  items text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table skills enable row level security;

create policy "Skills viewable by everyone." on skills for select using ( true );
create policy "Skills insertable by authenticated." on skills for insert with check ( auth.role() = 'authenticated' );
create policy "Skills updatable by authenticated." on skills for update using ( auth.role() = 'authenticated' );
create policy "Skills deletable by authenticated." on skills for delete using ( auth.role() = 'authenticated' );


-- INITIAL DATA INSERTION
-- Note: Profiles data usually linked to a specific user ID. 
-- For simplicity in this script, we won't insert the profile here as it requires the exact UUID.
-- The user can insert it via the UI or we can do it if we know the UUID.

-- Insert Experience
INSERT INTO experience (company, position, location, description, duration) VALUES
('MicroMerger Pvt Ltd', 'Software Engineer', 'Islamabad, Pakistan', 'Develop dynamic web applications using React.js, Next.js, and WordPress solutions with ACF. Convert Figma designs into pixel-perfect, responsive React components with strong attention to UI/UX. Implement SEO best practices. Build responsive dashboards using Ant Design, Material UI, Chakra UI. Work with Frappe and ERPNext frameworks.', 'Feb 2025 – Present'),
('Alphabase (US-based)', 'Frontend Development Intern', 'NSTP, Islamabad, Pakistan', 'Developed Qotion, a Notion-style collaborative table application. Converted Figma mockups into functional React components. Implemented state management using Jotai, Zustand, React Context API. Enhanced UI/UX on Zaplead.ai platform.', 'Nov 2024 – Feb 2025'),
('Juhuu Gmbh (Austria-based)', 'Frontend Developer', 'Remote', 'Designed, developed and maintained web applications using React.js, Tailwind CSS, and JavaScript. Built the JUHUU Marketplace and BikeBox websites, optimizing for performance and responsive design. Collaborated remotely with the JUHUU team.', 'Sep 2023 – Mar 2024'),
('BestMobile.pk', 'Social Media Manager', 'Remote', 'Managed social media strategy across multiple platforms. Created visual content using Photoshop and After Effects.', 'Jan 2020 – Jun 2024');

-- Insert Education
INSERT INTO education (degree, university, period) VALUES
('Bachelor of Science in Information Technology', 'University of Chakwal, Punjab, Pakistan', 'Oct 2020 – Sep 2024');

-- Insert Skills
INSERT INTO skills (category, items) VALUES
('Languages', ARRAY['TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'Python', 'PHP']),
('Frameworks', ARRAY['React.js', 'Next.js', 'Node.js', 'Express.js', 'WordPress']),
('UI Libraries', ARRAY['Tailwind CSS', 'Shadcn/UI', 'Ant Design', 'Material UI', 'Chakra UI', 'Radix UI', 'Framer Motion']),
('Tools', ARRAY['Git', 'GitHub', 'Vercel', 'Figma', 'Canva', 'Jira', 'Postman']),
('Database', ARRAY['MySQL', 'Firebase Firestore', 'MongoDB', 'IndexedDB']),
('Other', ARRAY['REST APIs', 'SEO', 'Responsive Design', 'Web Performance', 'ERPNext', 'Frappe']);

-- Insert Projects
INSERT INTO projects (name, description, tech, github_url, live_url, featured, year) VALUES
('PeekGamer', 'Game discovery platform with SSR, advanced search/filter, custom dark UI, and favorites saved via localStorage.', ARRAY['Next.js', 'TypeScript', 'Ant Design', 'RAWG API'], 'https://github.com/faheem506pk/PeekGamer', 'https://peekgamer.vercel.app', true, '2025'),
('StitchSmart', 'Tailor shop management system with role-based access, analytics, payments, and offline support using IndexedDB.', ARRAY['React', 'TypeScript', 'Firebase', 'Zustand'], 'https://github.com/Start-app/StitchSmart', 'https://stitchsmart.vercel.app', true, '2025'),
('Qotion', 'Notion-style table clone with drag-and-drop and real-time sync.', ARRAY['React', 'TypeScript', 'Firebase', 'Dnd-kit'], 'https://github.com/faheem506pk/Qotion', 'https://qotion.vercel.app', true, '2024'),
('KaTable App', 'Custom editable data table with localStorage persistence.', ARRAY['React', 'TypeScript', 'MUI', 'React Table'], 'https://github.com/faheem506pk/KaTable-App', 'https://katable-app.vercel.app', false, '2025'),
('PlantPulse', 'IoT-based greenhouse monitoring system with real-time sensor dashboard.', ARRAY['React', 'Firebase', 'ESP32', 'Recharts'], 'https://github.com/faheem506pk/PlantPulse', 'https://plantpulse-iot.vercel.app', false, '2024'),
('Cinematic Vistas', 'A modern movie browsing platform with responsive design, search functionality, and dynamic content integration.', ARRAY['React', 'TypeScript', 'Tailwind CSS', 'TMDB API'], 'https://github.com/faheem506pk/cinematic-vistas', 'https://cinematic-vistas.vercel.app', false, '2024'),
('ExplorePak', 'A tourism platform with admin panel for package and booking management.', ARRAY['PHP', 'MySQL', 'HTML5', 'Bootstrap'], 'https://github.com/faheem506pk/ExplorePak', 'https://explorepak.vercel.app', false, '2024'),
('Speedy Eats', 'A fully dynamic WordPress website with custom theme, ACF integration, and SEO optimization.', ARRAY['WordPress', 'ACF', 'PHP', 'JavaScript'], 'https://github.com/faheem506pk/speedy-eats', 'https://speedy-eats.vercel.app', true, '2025');
