-- Enable Row Level Security (RLS) is enabled by default on new tables in Supabase, but we explicity enable it.

-- DROP TABLES cleanup to ensure schema updates (like new columns) are applied
DROP TABLE IF EXISTS experience, projects, education, skills, profiles CASCADE;

-- 1. PROFILES TABLE (Single record for main user info)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null,
  role text,
  address text,
  phone text,
  email text,
  nationality text,
  summary text,
  social_linkedin text,
  social_github text,
  social_portfolio text,
  resume_url text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 2. EXPERIENCE TABLE (Enhanced)
create table if not exists experience (
  id bigint generated by default as identity primary key,
  company text not null,
  position text not null,
  location text,
  description text,
  duration text,
  is_development boolean default true,
  start_date date,
  end_date date,
  type text, -- Full-time, Internship, Freelance, Part-time
  skills text[], -- Array of skills used
  logo_url text, -- For company logo
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table experience enable row level security;

create policy "Experience viewable by everyone." on experience for select using ( true );
create policy "Experience insertable by authenticated." on experience for insert with check ( auth.role() = 'authenticated' );
create policy "Experience updatable by authenticated." on experience for update using ( auth.role() = 'authenticated' );
create policy "Experience deletable by authenticated." on experience for delete using ( auth.role() = 'authenticated' );

-- 3. PROJECTS TABLE
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  tech text[], -- Array of strings
  github_url text,
  live_url text,
  featured boolean default false,
  year text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;

create policy "Projects viewable by everyone." on projects for select using ( true );
create policy "Projects insertable by authenticated." on projects for insert with check ( auth.role() = 'authenticated' );
create policy "Projects updatable by authenticated." on projects for update using ( auth.role() = 'authenticated' );
create policy "Projects deletable by authenticated." on projects for delete using ( auth.role() = 'authenticated' );

-- 4. EDUCATION TABLE
create table if not exists education (
  id bigint generated by default as identity primary key,
  degree text not null,
  university text not null,
  period text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table education enable row level security;

create policy "Education viewable by everyone." on education for select using ( true );
create policy "Education insertable by authenticated." on education for insert with check ( auth.role() = 'authenticated' );
create policy "Education updatable by authenticated." on education for update using ( auth.role() = 'authenticated' );
create policy "Education deletable by authenticated." on education for delete using ( auth.role() = 'authenticated' );

-- 5. SKILLS TABLE
create table if not exists skills (
  id bigint generated by default as identity primary key,
  category text not null, -- e.g. "Languages", "Frameworks"
  items text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table skills enable row level security;

create policy "Skills viewable by everyone." on skills for select using ( true );
create policy "Skills insertable by authenticated." on skills for insert with check ( auth.role() = 'authenticated' );
create policy "Skills updatable by authenticated." on skills for update using ( auth.role() = 'authenticated' );
create policy "Skills deletable by authenticated." on skills for delete using ( auth.role() = 'authenticated' );


-- INITIAL DATA INSERTION (Updated with new experience data)

-- Clear existing data to avoid duplicates if re-running
TRUNCATE TABLE experience RESTART IDENTITY;
TRUNCATE TABLE projects RESTART IDENTITY;
TRUNCATE TABLE education RESTART IDENTITY;
TRUNCATE TABLE skills RESTART IDENTITY;

-- Insert Experience
INSERT INTO experience (company, position, location, type, duration, skills, description) VALUES
('MicroMerger (Pvt.) Ltd.', 'Software Engineer', 'Islāmābād, Pakistan · On-site', 'Full-time', 'Jan 2026 - Present', 
 ARRAY['React.js', 'ERP Next', 'Frappe', 'Node.js', 'JavaScript', 'Next.js', 'Git', 'GitHub', 'Linux', 'CLI', 'Bootstrap', 'Tailwind CSS', 'Ant Design', 'Firebase', 'REST APIs', 'MongoDB', 'PostgreSQL'], 
 'Full-stack development using React.js, Node.js, and Frappe/ERPNext ecosystem.'),

('MicroMerger (Pvt.) Ltd.', 'Associate Software Engineer', 'Islāmābād, Pakistan · On-site', 'Full-time', 'Feb 2025 - Jan 2026', 
 ARRAY['React.js', 'Tailwind CSS', 'JavaScript', 'REST APIs', 'PHP', 'Bootstrap', 'WordPress', 'TypeScript', 'Figma', 'Frappe'], 
 'Frontend development and assisting in ERP Next implementations.'),

('Intern Intelligence', 'Frontend Developer', 'Remote', 'Internship', 'Feb 2025 - Feb 2025', 
 ARRAY['React.js', 'JavaScript', 'HTML5', 'CSS3', 'Tailwind CSS', 'Ant Design', 'Bootstrap'], 
 'Frontend interface development for AI-driven applications.'),

('Alphabase', 'ReactJs / Frontend Developer', 'Islāmābād, Pakistan · Hybrid', 'Internship', 'Nov 2024 - Jan 2025', 
 ARRAY['React.js', 'CSS', 'Bootstrap', 'Web Development', 'Tailwind CSS', 'JavaScript', 'HTML'], 
 'Developed scalable frontend components and optimized web performance.'),

('Zaplead', 'ReactJs / Frontend Developer', 'Islāmābād, Pakistan · Hybrid', 'Internship', 'Nov 2024 - Jan 2025', 
 ARRAY['React.js', 'TypeScript', 'Gitlab', 'Tailwind CSS', 'UI/UX', 'State Management', 'KA-Table'], 
 'Built dynamic data tables and interactive dashboards using React and TypeScript.'),

('JUHUU', 'ReactJs Frontend Developer', 'Pakistan · Remote', 'Freelance', 'Jan 2024 - May 2024', 
 ARRAY['React.js', 'JavaScript', 'HTML', 'Frontend Development', 'Tailwind CSS'], 
 'Freelance frontend development for the JUHUU marketplace.'),

('JUHUU Marketplace', 'Web User Interface Developer', 'Pakistan · Remote', 'Freelance', 'Oct 2023 - Dec 2023', 
 ARRAY['Bootstrap', 'CSS', 'HTML', 'JavaScript', 'UI/UX', 'Web Design'], 
 'Designed and implemented user interfaces for web applications.'),

('BestMobile.pk', 'Social Media Manager', 'Pakistan · Hybrid', 'Part-time', 'May 2020 - Apr 2024', 
 ARRAY['Adobe Photoshop', 'Adobe Premiere Pro', 'After Effects', 'Data Analysis'], 
 'Managed social media channels and created visual content.');


-- Insert Education
INSERT INTO education (degree, university, period) VALUES
('Bachelor of Science in Information Technology', 'University of Chakwal, Punjab, Pakistan', 'Oct 2020 - Sep 2024');

-- Insert Skills
INSERT INTO skills (category, items) VALUES
('Languages', ARRAY['TypeScript', 'JavaScript', 'Python', 'PHP', 'HTML5', 'CSS3']),
('Frameworks', ARRAY['React.js', 'Next.js', 'Node.js', 'Express.js', 'WordPress', 'Frappe', 'ERPNext']),
('UI Libraries', ARRAY['Tailwind CSS', 'Ant Design', 'Shadcn/UI', 'Material UI', 'Chakra UI', 'Framer Motion']),
('Tools', ARRAY['Git', 'GitHub', 'GitLab', 'Vercel', 'Figma', 'Adobe Creative Suite', 'Postman']);

-- Insert Projects (Preserving existing projects)
INSERT INTO projects (name, description, tech, github_url, live_url, featured, year) VALUES
('PeekGamer', 'Game discovery platform with SSR, advanced search/filter, custom dark UI, and favorites saved via localStorage.', ARRAY['Next.js', 'TypeScript', 'Ant Design', 'RAWG API'], 'https://github.com/faheem506pk/PeekGamer', 'https://peekgamer.vercel.app', true, '2025'),
('StitchSmart', 'Tailor shop management system with role-based access, analytics, payments, and offline support using IndexedDB.', ARRAY['React', 'TypeScript', 'Firebase', 'Zustand'], 'https://github.com/Start-app/StitchSmart', 'https://stitchsmart.vercel.app', true, '2025'),
('Qotion', 'Notion-style table clone with drag-and-drop and real-time sync.', ARRAY['React', 'TypeScript', 'Firebase', 'Dnd-kit'], 'https://github.com/faheem506pk/Qotion', 'https://qotion.vercel.app', true, '2024'),
('KaTable App', 'Custom editable data table with localStorage persistence.', ARRAY['React', 'TypeScript', 'MUI', 'React Table'], 'https://github.com/faheem506pk/KaTable-App', 'https://katable-app.vercel.app', false, '2025'),
('PlantPulse', 'IoT-based greenhouse monitoring system with real-time sensor dashboard.', ARRAY['React', 'Firebase', 'ESP32', 'Recharts'], 'https://github.com/faheem506pk/PlantPulse', 'https://plantpulse-iot.vercel.app', false, '2024'),
('Cinematic Vistas', 'A modern movie browsing platform with responsive design, search functionality, and dynamic content integration.', ARRAY['React', 'TypeScript', 'Tailwind CSS', 'TMDB API'], 'https://github.com/faheem506pk/cinematic-vistas', 'https://cinematic-vistas.vercel.app', false, '2024'),
('ExplorePak', 'A tourism platform with admin panel for package and booking management.', ARRAY['PHP', 'MySQL', 'HTML5', 'Bootstrap'], 'https://github.com/faheem506pk/ExplorePak', 'https://explorepak.vercel.app', false, '2024'),
('Speedy Eats', 'A fully dynamic WordPress website with custom theme, ACF integration, and SEO optimization.', ARRAY['WordPress', 'ACF', 'PHP', 'JavaScript'], 'https://github.com/faheem506pk/speedy-eats', 'https://speedy-eats.vercel.app', true, '2025');

-- 6. MESSAGES TABLE
create table if not exists messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table messages enable row level security;

create policy "Messages insertable by everyone." on messages for insert with check ( true );
create policy "Messages viewable by authenticated." on messages for select using ( auth.role() = 'authenticated' );
create policy "Messages updatable by authenticated." on messages for update using ( auth.role() = 'authenticated' );
create policy "Messages deletable by authenticated." on messages for delete using ( auth.role() = 'authenticated' );
